In [1]:
'''In this notebook we will download all of the IBL video files and then compress them to 64x? pixels and 30fps
  then we will save them to a local folder from which we can run an http server'''
import numpy as np
import requests
import subprocess

In [2]:
from one.api import ONE
one = ONE(base_url='https://alyx.internationalbrainlab.org')

C:\Users\Dan\.conda\envs\iblenv\lib\site-packages\one\api.py:1294: UserWarning: Newer cache tables require ONE version 1.10.0 or greater
  warnings.warn(f'Newer cache tables require ONE version {min_version} or greater')


In [3]:
eid = '73918ae1-e4fd-4c18-b132-00cb555b1ad2'
print(eid)

73918ae1-e4fd-4c18-b132-00cb555b1ad2


In [4]:
with open('username.txt') as f:
    username = f.readlines()
    username = username[0]
with open('password.txt') as f:
    password = f.readlines()
    password = password[0]


In [26]:
dsets = one.type2datasets(eid, '_iblrig_Camera.raw', details=True)
videos = ['left','right','body']

# opener.addheaders[]

for video in videos:
  dset = next(d for idx, d in dsets.iterrows() if video in d['rel_path'])
  url = one.record2url(dset)
  print(url)
  ftext = eid + '_' + video
  # videoFile = 'flatironVideos/' +ftext + ".mp4"
  # open(videoFile, 'wb').write(requests.get(url, auth=(username, password)).content)
  # also get the timestamps
  # To get timestamps for video data so you can find out what times each frame is at
  dsets_time = one.type2datasets(eid, 'camera.times')
  dset = next(d for d in dsets_time if video in d)
  # load data
  times = one.load_dataset(eid, dset)
  print(len(times))
  print(1/np.diff(times))
  with open('C:\\proj\\VBL\\iblreplay-preproc\\data\\flatiron_videos\\'+ftext+'_times.txt','w') as f:
    f.write(str(times[0]))
  np.save('data/flatiron_videos/'+ftext+"_times.npy",times)
  # call = subprocess.call(['ffmpeg',
  #                '-i', 'C:\\proj\\VBL\\iblreplay-preproc\\flatironVideos\\'+ftext+'.mp4',
  #                '-vf', 'fps=30,scale=64:52', 
  #                'C:\\proj\\VBL\\iblreplay-preproc\\data\\flatiron_videos\\'+ftext+'_scaled'+'.mp4'])

https://ibl.flatironinstitute.org/wittenlab/Subjects/ibl_witten_27/2021-01-21/001/raw_video_data/_iblrig_leftCamera.raw.c29d01f9-3f65-4d09-86fe-43fcd0e85e30.mp4
251607
[60.12024048 60.         60.         ... 60.12024048 60.
 60.12024048]
https://ibl.flatironinstitute.org/wittenlab/Subjects/ibl_witten_27/2021-01-21/001/raw_video_data/_iblrig_rightCamera.raw.417ea728-8022-4656-863d-eda7f83a2a3f.mp4
628461
[150.         150.         150.         ... 150.00000001 149.99999999
 150.00000001]
https://ibl.flatironinstitute.org/wittenlab/Subjects/ibl_witten_27/2021-01-21/001/raw_video_data/_iblrig_bodyCamera.raw.a59ffd54-46d5-4560-a6e2-6847dbfdeca5.mp4
126332
[30.15075377 30.15075377 30.15075377 ... 30.12048193 30.15075377
 30.15075377]


In [10]:
np.diff(times)

array([0.03316667, 0.03316667, 0.03316667, ..., 0.0332    , 0.03316667,
       0.03316667])

In [29]:
time = np.load('data/flatiron_videos/'+eid + '_' + 'body' +"_times.npy")
np.mean(1/np.diff(times))

30.148357776257335

In [11]:
1/30

0.03333333333333333

In [12]:
1/60

0.016666666666666666

In [13]:
times[0:10]

array([101.2466    , 101.27976667, 101.31293333, 101.3461    ,
       101.37926667, 101.41243333, 101.4456    , 101.47876667,
       101.51193333, 101.5451    ])

In [35]:
print(times[0]+1/30.148*50000)
print(times[50000])

1759.731408279156
1759.7117666666666


In [19]:
1/np.diff(times)

array([30.15075377, 30.15075377, 30.15075377, ..., 30.12048193,
       30.15075377, 30.15075377])